server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:h2:mem:localdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
